name: Metrics
on:
  # Roda a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configurações para gerar APENAS as linguagens
          user: vinicius-b-oliveira
          template: classic
          base: "" # Desativa o cabeçalho padrão (0 orgs, seguidores, etc)
          config_timezone: America/Sao_Paulo
          
          # Configuração das Linguagens
          plugin_languages: yes
          plugin_languages_ignored: html, css, blade # Ignora linguagens de marcação se quiser
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_details: percentage
          
          # Visual
          config_padding: 0, 10 + 5% # Ajuste de espaçamento
          filename: github-metrics.svg
          committer_branch: metrics
          committer_message: "chore: update metrics"
